#!/bin/bash

IMAGEDIR="/home/mdoob/mblinalg/images"
XMLFILE="/home/mdoob/mblinalg/mblinalg.xml"

echo "Image directory is " $IMAGEDIR
echo "xml file is " $XMLFILE

# -vv option gives more details
# /home/mdoob/mathbook/pretext/pretext -vv -c asy -f html -d $IMAGEDIR $XMLFILE
/home/mdoob/mathbook/pretext/pretext -v -c asy -f html -d $IMAGEDIR $XMLFILE



