#!/bin/bash

IMAGEDIR="/home/mdoob/mblinalg/images"
XMLFILE="/home/mdoob/mblinalg/mblinalg.xml"

echo "IMAGEDIR is " $IMAGEDIR
echo "XMLFILE is " $XMLFILE

# -vv option gives more details
/home/mdoob/mathbook/pretext/pretext -vv -c asy -f html -d $IMAGEDIR $XMLFILE



