#!/bin/bash
#
# Imitation of the mbx conversion command
#

for sfile in *.pdf
do
dfile=`basename $sfile ".pdf"`.svg
    if [ $sfile -nt  $dfile ] 
    then
    echo Converting $sfile to $dfile
    /usr/bin/pdf2svg $sfile $dfile
# uncomment next line to automatically remove the pdf files
#   rm $sfile
    fi
done

